# Generated by Django 2.2.12 on 2022-11-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('postoffice', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
