# Generated by Django 2.2.12 on 2022-11-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221122_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='Address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Address'),
            preserve_default=False,
        ),
    ]
