# Generated by Django 2.2.12 on 2022-11-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Technician.Test'),
        ),
    ]
