# Generated by Django 2.2.12 on 2022-11-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('Technician', '0002_auto_20221106_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Lab')),
            ],
        ),
    ]
