# Generated by Django 2.2.12 on 2022-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0004_token_current_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
