# Generated by Django 2.2.12 on 2022-11-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0006_auto_20221112_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
