# Generated by Django 2.2.12 on 2022-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0009_auto_20221112_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(max_length=50),
        ),
    ]
