# Generated by Django 2.2.12 on 2022-11-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0013_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
