# Generated by Django 2.2.12 on 2022-11-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0015_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='lab',
        ),
    ]
