# Generated by Django 2.2.12 on 2022-11-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('Technician', '0016_remove_token_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='labs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Lab'),
            preserve_default=False,
        ),
    ]
