# Generated by Django 2.2.12 on 2022-11-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0017_token_labs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='labs',
            new_name='lab',
        ),
    ]
